# Copyright 2026 Jaqueline Martins / Sovereign Chain Ltd.
# SPDX-License-Identifier: Apache-2.0
"""Email notifier — sends owner a digest of pending drafts.

Default transport: Gmail SMTP via app password. Owner sets:
  PROACTIVE_NOTIFY_FROM   = sender Gmail address
  PROACTIVE_NOTIFY_TO     = where to send the digest (often the same)
  PROACTIVE_SMTP_PASSWORD = Gmail App Password (16 chars, generated at
                            https://myaccount.google.com/apppasswords)

The digest contains, per draft:
  - signal preview (source, author, snippet, link)
  - intent score + rationale
  - draft kind + target
  - the draft body
  - 3 magic links: APPROVE / EDIT / REJECT (point at the local web
    review UI; for the MVP these are just mailto: links the owner
    clicks to reply with the action code)

Cloud Run / SMTP: Cloud Run blocks port 25 outbound. Gmail SMTP uses
587 (STARTTLS) which IS open. So this works there too.
"""

from __future__ import annotations

import logging
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Sequence

logger = logging.getLogger(__name__)


def _env(name: str, default: str = "") -> str:
    return os.getenv(name, default).strip()


# --------------------------------------------------------------------------- #
# Digest rendering                                                             #
# --------------------------------------------------------------------------- #


def render_digest_html(drafts: Sequence[dict], *, base_url: str = "") -> str:
    """Render N pending drafts as an HTML email body.

    Each draft gets approve/reject/edit mailto-or-link buttons. When
    ``base_url`` is given (e.g. https://quorum-ai.dev/proactive),
    buttons point at the web UI; otherwise they're mailto: with the
    action code in the subject for manual processing.
    """
    if not drafts:
        return _empty_html()
    rows = []
    for d in drafts:
        rows.append(_render_one(d, base_url))
    n = len(drafts)
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body {{ font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        color: #222; max-width: 720px; margin: 24px auto; padding: 0 16px; }}
h1 {{ font-size: 20px; border-bottom: 2px solid #333; padding-bottom: 8px; }}
.card {{ border: 1px solid #ddd; border-radius: 6px; padding: 16px; margin: 18px 0;
         background: #fafafa; }}
.meta {{ color: #666; font-size: 12px; margin-bottom: 8px; }}
.score-high {{ color: #0a7c2f; font-weight: 600; }}
.score-mid {{ color: #b06a00; font-weight: 600; }}
.score-low {{ color: #999; }}
pre.body {{ white-space: pre-wrap; background: #fff; border: 1px solid #eee;
            padding: 10px; border-radius: 4px; font: 13px/1.4 ui-monospace, monospace; }}
.btn {{ display: inline-block; padding: 8px 14px; margin: 4px 4px 0 0;
        text-decoration: none; border-radius: 4px; font-weight: 600; font-size: 13px; }}
.btn-ok {{ background: #0a7c2f; color: white; }}
.btn-no {{ background: #c62828; color: white; }}
.btn-edit {{ background: #2962ff; color: white; }}
.rationale {{ font-style: italic; color: #555; margin: 6px 0; }}
.source-link {{ color: #2962ff; }}
</style></head><body>
<h1>Quorum Proactive — {n} draft{"s" if n != 1 else ""} pending review</h1>
<p style="color: #666;">Sorted by intent score (best first). Click APPROVE to send, REJECT to drop, EDIT to tweak first.</p>
{"".join(rows)}
<p style="color: #999; font-size: 11px; margin-top: 32px;">
Generated by Quorum Proactive · audit chain SHA-256 on each row · NEVER auto-executes.
</p>
</body></html>"""


def _empty_html() -> str:
    return """<!DOCTYPE html>
<html><body style="font: 14px/1.5 sans-serif; max-width: 600px; margin: 32px auto;">
<h1 style="font-size: 18px;">Quorum Proactive — nothing pending</h1>
<p>No drafts above the score threshold today. Either Quorum saw nothing
interesting, or your filters are too tight.</p>
</body></html>"""


def _render_one(d: dict, base_url: str) -> str:
    score = float(d.get("intent_score", 0.0))
    cls = "score-high" if score >= 0.7 else "score-mid" if score >= 0.4 else "score-low"
    draft_id = d.get("id", "")

    if base_url:
        approve = f'<a class="btn btn-ok" href="{base_url}/approve/{draft_id}">✓ APPROVE</a>'
        reject = f'<a class="btn btn-no" href="{base_url}/reject/{draft_id}">✗ REJECT</a>'
        edit = f'<a class="btn btn-edit" href="{base_url}/edit/{draft_id}">✎ EDIT</a>'
    else:
        from urllib.parse import quote
        to = _env("PROACTIVE_NOTIFY_TO", "")
        approve = f'<a class="btn btn-ok" href="mailto:{to}?subject={quote("[QUORUM-APPROVE] " + draft_id)}">✓ APPROVE</a>'
        reject = f'<a class="btn btn-no" href="mailto:{to}?subject={quote("[QUORUM-REJECT] " + draft_id)}">✗ REJECT</a>'
        edit = f'<a class="btn btn-edit" href="mailto:{to}?subject={quote("[QUORUM-EDIT] " + draft_id)}&body={quote(d.get("body",""))}">✎ EDIT</a>'

    sig_url = d.get("signal_url", "")
    src = d.get("signal_source", "?")
    author = d.get("signal_author", "?")
    sig_title = (d.get("signal_title") or "")[:160]
    rationale = d.get("rationale", "")
    kind = d.get("kind", "?")
    target = d.get("target", "?")
    body = (d.get("body") or "")[:2000]

    sig_link = f' · <a class="source-link" href="{sig_url}">link</a>' if sig_url else ""

    return f"""<div class="card">
<div class="meta">
  <span class="{cls}">{score:.2f}</span> intent ·
  <b>{src}</b> · {author} · {kind} → {target}{sig_link}
</div>
<div><b>Signal:</b> {sig_title}</div>
<div class="rationale">{rationale}</div>
<pre class="body">{body}</pre>
<div>{approve} {edit} {reject}</div>
</div>"""


# --------------------------------------------------------------------------- #
# SMTP send                                                                    #
# --------------------------------------------------------------------------- #


def send_digest(html: str, *, subject: str = "Quorum Proactive — pending review") -> bool:
    """Send the digest via Gmail SMTP. Returns True on success."""
    sender = _env("PROACTIVE_NOTIFY_FROM")
    recipient = _env("PROACTIVE_NOTIFY_TO") or sender
    password = _env("PROACTIVE_SMTP_PASSWORD")
    if not sender or not password:
        logger.warning("notifier.skipped reason=missing_env "
                       "(PROACTIVE_NOTIFY_FROM/PROACTIVE_SMTP_PASSWORD)")
        return False

    msg = MIMEMultipart("alternative")
    msg["From"] = sender
    msg["To"] = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(_strip_html_tags(html), "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    ctx = ssl.create_default_context()
    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=20) as server:
            server.starttls(context=ctx)
            server.login(sender, password)
            server.sendmail(sender, [recipient], msg.as_string())
        logger.info("notifier.sent to=%s subject=%s", recipient, subject)
        return True
    except Exception as e:  # noqa: BLE001
        logger.error("notifier.send_failed err=%s", e)
        return False


def _strip_html_tags(s: str) -> str:
    import re
    return re.sub(r"<[^>]+>", " ", s)


__all__ = ["render_digest_html", "send_digest"]
